### PR TITLE
support sulu 1.3 version

### PR DESCRIPTION
**Pull request by nickvanderzwet**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #issuenum
| Related issues/PRs | #issuenum
| License | MIT
| Documentation PR | sulu/sulu-docs#prnum

#### What's in this PR?

Added sulu 1.3 in composer.json

#### Why?

Can't use this bundle with the latest sulu version 1.3 (only with dev-develop)

### CODE REVIEW

**Comment by nickvanderzwet** [comment]
@wachterjohannes Yes, we already are using it with 1.3.. 
Don't know if #4 will work with 1.3, didn't test it yet.

**Comment by wachterjohannes** [comment]
@nickvanderzwet i have tested it today and it seems to work (: also with the UI. i will merge this tomorrow!

**Comment by wachterjohannes** [comment]
@nickvanderzwet sorry for the delay (: thanks for the contribution. if you have questions feel free to ask!

**Comment by nickvanderzwet** [comment]
Thanks! I will add the new version to my project today

**Pull request merged**
